### ISSUE TITLE
FEATURE REQUEST: User defined examples

### ISSUE THREAD

**Issue by gojzdar** [dvinciguerra/tldr-cli#2]
Allow users to create local usage examples for specific tldr entries.

I use a few commands all the time, but can't remember the syntax for. So I look at the tldr page, only to realize the exact use case I need isn't documented. I could post a pull request to tldr-pages, but "polluting" the tldr pages viewed by thousands with my specific usage cases wouldn't be ideal.  
I know I can just edit the pages manually in .local/share/, or write a script that appends my changes after every update, but I would prefer for it to be more organized, portable and future proof. I also doubt I am the only one with this problem.

**Comment by dvinciguerra** [comment]
Sounds greate, thanks for your issue!

Feature accepted.

**Comment by dvinciguerra** [comment]
Done at v0.3.0

https://github.com/dvinciguerra/tldr-cli/releases/tag/v0.3.0
